# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备名称')),
                ('device_status', models.IntegerField(choices=[(0, '关'), (1, '开')], default=0, verbose_name='设备状态')),
            ],
        ),
    ]
